In [50]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import train_test_split
from scipy.io import arff
import pandas as pd

df = pd.read_csv("C:/Users/Vineet Kumar/Downloads/kidnapping.csv")
df.head()

,STATE/UT,YEAR,Purpose,Total No. of cases reported,Male upto 10 years,Female upto 10 years,Male 10-15 years,Female 10-15 years,Male 15-18 years,Female 15-18 years,...,Female 30-50 years,Male above 50 years,Female above 50 years,Total Male,Total Female,Grand Total,Male below 18,Female below 18,Number of children,Label
0,Andhra Pradesh,2001,For Adoption,8,3,1,0,0,0,0,...,0,0,0,3,5,8,3,1,4,F
1,Andhra Pradesh,2001,For Begging,2,0,0,2,0,0,0,...,0,0,0,2,0,2,2,0,2,M
2,Andhra Pradesh,2001,For Camel racing,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,F
3,Andhra Pradesh,2001,For Illicit intercourse,78,0,2,0,25,0,24,...,2,0,0,0,78,78,0,51,51,F
4,Andhra Pradesh,2001,For marriage,339,0,0,0,73,1,164,...,4,0,0,7,332,339,1,237,238,F

In [51]:
df = df.drop(['Total No. of cases reported'], axis=1)
df = df.drop(['Male upto 10 years'], axis=1)
df = df.drop(['Female upto 10 years'], axis=1)
df = df.drop(['Male 10-15 years'], axis=1)
df = df.drop(['Female 10-15 years'], axis=1)
df = df.drop(['Male 15-18 years'], axis=1)
df = df.drop(['Female 15-18 years'], axis=1)
df = df.drop(['Total Male'], axis=1)
df = df.drop(['Female below 18'], axis=1)
df = df.drop(['Total Female'], axis=1)
df = df.drop(['Number of children'], axis=1)
df = df.drop(['Label'], axis=1)

df.head()

,STATE/UT,YEAR,Purpose,Male 18-30 years,Female 18-30 years,Male 30-50 years,Female 30-50 years,Male above 50 years,Female above 50 years,Grand Total,Male below 18
0,Andhra Pradesh,2001,For Adoption,0,4,0,0,0,0,8,3
1,Andhra Pradesh,2001,For Begging,0,0,0,0,0,0,2,2
2,Andhra Pradesh,2001,For Camel racing,0,0,0,0,0,0,0,0
3,Andhra Pradesh,2001,For Illicit intercourse,0,25,0,2,0,0,78,0
4,Andhra Pradesh,2001,For marriage,6,91,0,4,0,0,339,1

In [52]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def encode_df(dataframe):
    le = LabelEncoder()
    for column in dataframe.columns:
        dataframe[column] = le.fit_transform(dataframe[column])
    return dataframe

#encode the dataframe
data=encode_df(df)

print(data)

      STATE/UT  YEAR  Purpose  Male 18-30 years  Female 18-30 years  \
0            1     0        0                 0                   4
1            1     0        1                 0                   0
2            1     0        2                 0                   0
3            1     0        3                 0                  25
4            1     0       10                 6                  91
5            1     0        4                 0                  16
6            1     0        5                 2                   0
7            1     0        6                11                   4
8            1     0        7                 0                   0
9            1     0        8                 0                   0
10           1     0        9                 0                   0
11           1     0       11                54                  52
12           1     0       13               140                 146
13           1     0       14               182                 255
14           1     1        0                 0                   0
15           1     1        1                 4                   1
16           1     1        2                 0                   0
17           1     1        3                 0                  89
18           1     1       10                 0                 247
19           1     1        4                 0                  49
20           1     1        5                 4                   0
21           1     1        6                 6                  15
22           1     1        7                 0                   1
23           1     1        8                 0                   0
24           1     1        9                 0                   3
25           1     1       11                45                  41
26           1     1       13               190                 164
27           1     1       14               214                 386
28           1     2        0                 0                   0
29           1     2        1                 0                   0
...        ...   ...      ...               ...                 ...
5836        26     9       13                 0                   0
5837        26     9       14                 1                   6
5838        26    10        0                 0                   0
5839        26    10        1                 0                   0
5840        26    10        2                 0                   0
5841        26    10        3                 0                   1
5842        26    10       10                 0                   0
5843        26    10        4                 0                   0
5844        26    10        5                 0                   0
5845        26    10        6                 0                   0
5846        26    10        7                 0                   0
5847        26    10        8                 0                   0
5848        26    10        9                 0                   0
5849        26    10       11                 1                   1
5850        26    10       13                 0                   0
5851        26    10       14                 1                   2
5852        26    11        0                 0                   0
5853        26    11        1                 0                   0
5854        26    11        2                 0                   0
5855        26    11        3                 0                   0
5856        26    11       10                 0                   1
5857        26    11        4                 0                   0
5858        26    11        5                 0                   0
5859        26    11        6                 0                   0
5860        26    11        7                 0                   0
5861        26    11        8                 0                   0
5862        26    11        9                 0                   0
5863        26    11       11                 0                   0
5864        26    11       13                 0                   0
5865        26    11       14                 0                   1

      Male 30-50 years  Female 30-50 years  Male above 50 years  \
0                    0                   0                    0
1                    0                   0                    0
2                    0                   0                    0
3                    0                   2                    0
4                    0                   4                    0
5                    0                   2                    0
6                    1                   0                    0
7                   12                   1                    0
8                    0                   0                    0
9                    0                   0                    0
10                   0                   0                    0
11                  26                   5                    2
12                  80                  11                    3
13                 114                  25                    5
14                   0                   0                    0
15                   0                   0                    0
16                   0                   0                    0
17                   0                   8                    0
18                   3                   4                    0
19                   0                   5                    0
20                   1                   0                    0
21                   2                   2                    3
22                   0                   0                    0
23                   0                   0                    0
24                   0                   0                    0
25                  11                   5                    6
26                 104                  27                    4
27                 118                  51                   13
28                   0                   0                    0
29                   0                   0                    0
...                ...                 ...                  ...
5836                 0                   0                    0
5837                 1                   0                    0
5838                 0                   0                    0
5839                 0                   0                    0
5840                 0                   0                    0
5841                 0                   0                    0
5842                 0                   0                    0
5843                 0                   0                    0
5844                 0                   0                    0
5845                 0                   0                    0
5846                 0                   0                    0
5847                 0                   0                    0
5848                 0                   0                    0
5849                 1                   1                    0
5850                 0                   0                    0
5851                 1                   1                    0
5852                 0                   0                    0
5853                 0                   0                    0
5854                 0                   0                    0
5855                 0                   0                    0
5856                 0                   0                    0
5857                 0                   0                    0
5858                 0                   0                    0
5859                 0                   0                    0
5860                 0                   0                    0
5861                 0                   0                    0
5862                 0                   0                    0
5863                 0                   0                    0
5864                 0                   0                    0
5865                 0                   0                    0

      Female above 50 years  Grand Total  Male below 18
0                         0            8              3
1                         0            2              2
2                         0            0              0
3                         0           78              0
4                         0          278              1
5                         0           36              0
6                         0           13              7
7                         0           47             11
8                         0            0              0
9                         0            0              0
10                        0            0              0
11                        0          164             23
12                        0          358             45
13                        0          552             86
14                        0            0              0
15                        0            6              1
16                        0            0              0
17                        0           98              0
18                        0          302              0
19                        0           61              0
20                        0            8              2
21                        0           34              4
22                        0            3              1
23                        0            0              0
24                        0            3              0
25                        0          107              0
26                        9          386              5
27                        9          571             13
28                        0            0              0
29                        0            1              0
...                     ...          ...            ...
5836                      0            0              0
5837                      0           20              2
5838                      0            0              0
5839                      0            0              0
5840                      0            0              0
5841                      0            1              0
5842                      0            5              0
5843                      0            0              0
5844                      0            1              1
5845                      0            0              0
5846                      0            0              0
5847                      0            0              0
5848                      0            0              0
5849                      0            5              0
5850                      0            0              0
5851                      0           12              1
5852                      0            0              0
5853                      0            0              0
5854                      0            0              0
5855                      0            0              0
5856                      0           11              0
5857                      0            0              0
5858                      0            0              0
5859                      0            0              0
5860                      0            0              0
5861                      0            0              0
5862                      0            0              0
5863                      0            0              0
5864                      0            8              3
5865                      0           19              3

[5866 rows x 11 columns]

In [53]:
X = df.iloc[:, df.columns != '2']
#X = df.iloc[:, 0:4].values 
y = df.iloc[:, 2].values

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

In [55]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  """

In [56]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [57]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[214   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 201   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 207   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 201   1   1   0   0   0   0   0   0   0   0]
 [  0   0   0   1 208   6   0   0   0   0   0   0   0   0]
 [  0   0   0   1   3 201   0   0   0   0   0   0   1   0]
 [  0   0   0   0   0   0 195   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   7 218   0   1   1   0   0   0]
 [  0   0   0   0   0   0   0   3 213   0   0   0   0   0]
 [  0   0   0   0   0   0   1   2   0 206   1   2   0   0]
 [  0   0   0   0   0   0   0   0   0   1 214   0   0   0]
 [  0   0   0   0   0   0   0   0   0   2   2 191   2   1]
 [  0   0   0   0   0   0   0   0   0   0   2  10 202   4]
 [  0   0   0   0   0   0   0   0   0   0   1   2   1 202]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       214
           1       1.00      1.00      1.00       201
           2       1.00      1.00      1.00       207
           3       0.99      0.99      0.99       203
           4       0.98      0.97      0.97       215
           5       0.97      0.98      0.97       206
           6       0.96      1.00      0.98       195
           7       0.98      0.96      0.97       227
           8       1.00      0.99      0.99       216
           9       0.98      0.97      0.98       212
          10       0.97      1.00      0.98       215
          11       0.93      0.96      0.95       198
          13       0.98      0.93      0.95       218
          14       0.98      0.98      0.98       206

   micro avg       0.98      0.98      0.98      2933
   macro avg       0.98      0.98      0.98      2933
weighted avg       0.98      0.98      0.98      2933

0.9795431299011251

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6, random_state=0)

In [59]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  """

In [60]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [61]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[247   0   0   1   0   0   0   0   0   0   0   0   0   0]
 [  0 243   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 259   1   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 249   1   1   0   0   0   0   0   0   0   0]
 [  0   0   0   2 248   7   0   0   0   0   0   0   0   0]
 [  0   0   0   0   2 238  10   0   0   0   1   0   1   0]
 [  0   0   0   0   1   3 218   2   0   0   0   0   0   0]
 [  0   0   0   0   2   0   9 257   1   1   2   0   0   0]
 [  0   0   0   0   0   0   1   3 260   0   0   0   0   0]
 [  0   0   0   0   0   0   1   3   1 237   2   6   0   0]
 [  0   0   0   0   0   0   0   0   0   1 252   0   0   0]
 [  0   0   0   0   0   0   0   0   0   2   1 230   4   1]
 [  0   0   0   0   0   0   0   0   0   0   3  12 241   2]
 [  0   0   0   0   0   0   0   0   0   0   0   7   3 240]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       248
           1       1.00      1.00      1.00       243
           2       1.00      1.00      1.00       260
           3       0.98      0.99      0.99       251
           4       0.98      0.96      0.97       257
           5       0.96      0.94      0.95       252
           6       0.91      0.97      0.94       224
           7       0.97      0.94      0.96       272
           8       0.99      0.98      0.99       264
           9       0.98      0.95      0.97       250
          10       0.97      1.00      0.98       253
          11       0.90      0.97      0.93       238
          13       0.97      0.93      0.95       258
          14       0.99      0.96      0.97       250

   micro avg       0.97      0.97      0.97      3520
   macro avg       0.97      0.97      0.97      3520
weighted avg       0.97      0.97      0.97      3520

0.9713068181818182

In [62]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=0)

In [63]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  """

In [64]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [65]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[296   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1 274   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 304   2   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 298   1   2   0   0   0   0   1   0   0   0]
 [  0   0   0   2 277  11   0   0   0   0   0   0   0   0]
 [  0   0   0   1   5 279   3   0   0   0   1   0   1   0]
 [  0   0   0   1   3   2 264   7   0   0   0   1   0   0]
 [  0   0   0   0   1   0  13 290   0   0   1   0   1   0]
 [  0   0   0   0   0   0   2   2 305   0   0   0   0   0]
 [  0   0   0   0   0   0   2   1   1 281   0   6   0   0]
 [  0   0   0   0   0   0   0   0   0   3 286   0   0   0]
 [  0   0   0   0   0   0   0   0   0   1   3 272   5   1]
 [  0   0   0   0   0   0   0   0   0   0   2  14 276   5]
 [  0   0   0   0   0   0   0   0   0   0   1  11   8 276]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       296
           1       1.00      1.00      1.00       275
           2       1.00      0.99      1.00       306
           3       0.98      0.99      0.98       302
           4       0.97      0.96      0.96       290
           5       0.95      0.96      0.96       290
           6       0.93      0.95      0.94       278
           7       0.97      0.95      0.96       306
           8       1.00      0.99      0.99       309
           9       0.99      0.97      0.98       291
          10       0.97      0.99      0.98       289
          11       0.89      0.96      0.93       282
          13       0.95      0.93      0.94       297
          14       0.98      0.93      0.96       296

   micro avg       0.97      0.97      0.97      4107
   macro avg       0.97      0.97      0.97      4107
weighted avg       0.97      0.97      0.97      4107

0.9685902118334551

In [66]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=0)

In [67]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  """

In [68]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [69]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[332   0   0   0   0   1   0   0   0   0   0   0   0   0]
 [  0 330   0   1   0   0   0   0   0   0   0   0   0   0]
 [  0   0 349   3   0   0   0   0   0   0   0   0   0   0]
 [  0   0   2 332   2   2   0   0   0   0   1   0   0   0]
 [  0   0   0   8 317   9   0   0   0   0   0   0   0   0]
 [  0   0   0   5  21 292   6   1   0   0   1   0   1   0]
 [  0   0   0   1   4   4 309  10   0   0   0   1   0   0]
 [  0   0   0   0   2   0  23 319   1   1   2   0   1   0]
 [  0   0   0   0   0   0   2   0 335   0   2   0   0   0]
 [  0   0   0   0   0   1  17   3   1 304   3   7   0   0]
 [  0   0   0   0   0   0   0   1   0   2 329   0   0   0]
 [  0   0   0   0   0   0   0   1   0   1   7 304   8   1]
 [  0   0   0   0   0   0   0   1   0   0   5  20 306   6]
 [  0   0   0   0   0   0   0   0   0   0   0  10   7 315]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       333
           1       1.00      1.00      1.00       331
           2       0.99      0.99      0.99       352
           3       0.95      0.98      0.96       339
           4       0.92      0.95      0.93       334
           5       0.94      0.89      0.92       327
           6       0.87      0.94      0.90       329
           7       0.95      0.91      0.93       349
           8       0.99      0.99      0.99       339
           9       0.99      0.90      0.94       336
          10       0.94      0.99      0.96       332
          11       0.89      0.94      0.92       322
          13       0.95      0.91      0.93       338
          14       0.98      0.95      0.96       332

   micro avg       0.95      0.95      0.95      4693
   macro avg       0.95      0.95      0.95      4693
weighted avg       0.95      0.95      0.95      4693

0.9531216705731941

In [70]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9, random_state=0)

In [71]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Vineet Kumar\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  """

In [72]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
classifier = RandomForestClassifier(n_estimators=100, random_state=0) 

#Train the model using the training sets y_pred=clf.predict(X_test)
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [73]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#Import scikit-learn metrics module for accuracy calculation

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 

# Model Accuracy, how often is the classifier correct?
print(accuracy_score(y_test, y_pred))

[[374   0   0   4   0   5   0   0   0   0   0   0   0   0]
 [  9 363   0   2   0   0   0   0   0   0   0   0   0   0]
 [  0   0 382   4   0   0   0   0   0   0   0   0   0   0]
 [  0   0  16 340  14   2   0   0   0   0   4   0   0   0]
 [  0   0   0  39 329  10   0   0   0   0   0   0   0   0]
 [  0   0   0  12   8 321  23   5   0   0   0   1   3   0]
 [  0   0   0   0   4  14 338   8   0   0   0   0   3   0]
 [  0   0   0   2   8   5  25 335   2   3   8   0   1   0]
 [  0   0   0   0   0   1   1   0 378   0   1   0   0   0]
 [  0   0   0   0   0   1  15   1   1 347   5   9   0   0]
 [  0   0   0   1   0   0   0   0   0   0 354  16   2   0]
 [  0   0   0   0   0   0   0   1   0   1  15 339  15   0]
 [  0   0   0   0   0   0   0   0   0   0  16  37 326   3]
 [  0   0   0   0   0   0   0   0   0   0   5   8   0 355]]
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       383
           1       1.00      0.97      0.99       374
           2       0.96      0.99      0.97       386
           3       0.84      0.90      0.87       376
           4       0.91      0.87      0.89       378
           5       0.89      0.86      0.88       373
           6       0.84      0.92      0.88       367
           7       0.96      0.86      0.91       389
           8       0.99      0.99      0.99       381
           9       0.99      0.92      0.95       379
          10       0.87      0.95      0.91       373
          11       0.83      0.91      0.87       371
          13       0.93      0.85      0.89       382
          14       0.99      0.96      0.98       368

   micro avg       0.92      0.92      0.92      5280
   macro avg       0.93      0.92      0.92      5280
weighted avg       0.93      0.92      0.92      5280

0.9244318181818182